# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           app
destination:      gh-pages
host:             0.0.0.0
port:             9000
#url:              http://code-wachid.com
encoding:         UTF-8